### ISSUE TITLE
ngrok is not yet ready to start tunnels

### ISSUE THREAD

**Issue by thirota** [thirota/ngrok-study#1]
```
$ npm start

> hirodevrgrokstudy@0.0.1 start /Users/takayuki/Work/ngrok-study
> node app.js

listening at http://:::3000
{ Error: ngrok is not yet ready to start tunnels
    at Request._callback (/Users/takayuki/Work/ngrok-study/node_modules/ngrok/index.js:192:30)
    at Request.self.callback (/Users/takayuki/Work/ngrok-study/node_modules/request/request.js:185:22)
    at emitTwo (events.js:106:13)
    at Request.emit (events.js:191:7)
    at Request.<anonymous> (/Users/takayuki/Work/ngrok-study/node_modules/request/request.js:1154:10)
    at emitOne (events.js:96:13)
    at Request.emit (events.js:188:7)
    at IncomingMessage.<anonymous> (/Users/takayuki/Work/ngrok-study/node_modules/request/request.js:1076:12)
    at IncomingMessage.g (events.js:291:16)
    at emitNone (events.js:91:20)
  error_code: 104,
  status_code: 503,
  msg: 'ngrok is not yet ready to start tunnels',
  details: { err: 'a successful ngrok tunnel session has not yet been established' } }
undefined

```

**Comment by thirota** [comment]
Mac Book Air (2011)
High Sierra

**Comment by thirota** [comment]
I can reproduce this problem on another mac.

* Mac Book
* Catalina
* Node v10.18.0
* npm 6.13.4

**Comment by thirota** [comment]
I can reproduce this on CentOS7 too.

* CentOS 7.3 (Vagrant bento/centos-7.3)
* Node v6.17.1 (yum install epel-release -> yum install nodejs)

**Comment by thirota** [comment]
It seems like 503 error has been occurred since July 2019.
